### ISSUE TITLE
2023/1/15 更動 Navbar.scss & Footer.scss

### ISSUE THREAD

**Issue by Echelon0815** [LINECHITAUBOOKING/LineChiTauFE#4]
## Navbar.scss 
```css=
@import '../../css/global-style.scss';
@import url('https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200');
.material-symbols-outlined {
  font-variation-settings: 'FILL' 1, 'wght' 700, 'GRAD' 0, 'opsz' 48;
  font-size: 28px;
}

.container-fluid {
  background-color: $secondary;
  padding: 0;
}

.navbar {
  width: 1920px;
  .logo-box {
    padding-top: 13px;
    .logo {
      height: 80px;
    }
  }
  .cart {
    width: 63px;
    height: 47px;
  }
}
```
## Footer.scss 
```css=
@import '../../css/global-style.scss';

.container-fluid {
  padding: 0;
  background-color: $secondary;
  // height: 150px;
}

.footer {
  max-width: 1920;
  .my-p {
    line-height: 28px;
  }

  .logo {
    height: 100px;
  }
}
```
